install app data without cloud-config

diff --git a/src/coreos-offline-install b/src/coreos-offline-install
--- a/src/coreos-offline-install
+++ b/src/coreos-offline-install
@@ -125,42 +125,40 @@ fi
 blockdev --rereadpt "${DEVICE}"
 
 
-if [[ -n "${CLOUDINIT}" ]]; then
-    # The ROOT partition should be #9 but make no assumptions here!
-    # Also don't mount by label directly in case other devices conflict.
-    ROOT_DEV=$(blkid -t "LABEL=ROOT" -o device "${DEVICE}"*)
+# The ROOT partition should be #9 but make no assumptions here!
+# Also don't mount by label directly in case other devices conflict.
+ROOT_DEV=$(blkid -t "LABEL=ROOT" -o device "${DEVICE}"*)
 
-    if [[ -z "${ROOT_DEV}" ]]; then
-        echo "Unable to find new ROOT partition on ${DEVICE}" >&2
-        exit 1
-    fi
-
-    mkdir -p "${WORKDIR}/rootfs"
-    case $(blkid -t "LABEL=ROOT" -o value -s TYPE "${ROOT_DEV}") in
-      "btrfs") mount -t btrfs -o subvol=root "${ROOT_DEV}" "${WORKDIR}/rootfs" ;;
-      *)       mount "${ROOT_DEV}" "${WORKDIR}/rootfs" ;;
-    esac
-    trap "umount '${WORKDIR}/rootfs' && rm -rf '${WORKDIR}'" EXIT
-
-    # resize filesystems
-    echo "Resize filesystems..."
-    /usr/lib64/coreos/extend-filesystems
-
-    if [[ -n "${CLOUDINIT}" ]]; then
-      echo "Installing cloud-config..."
-      mkdir -p "${WORKDIR}/rootfs/var/lib/coreos-install"
-      cp "${CLOUDINIT}" "${WORKDIR}/rootfs/var/lib/coreos-install/user_data"
-    fi
-
-    if [[ -n "${APPDATA}" ]]; then
-      echo "Installing appdata to /app..."
-      mkdir -p "${WORKDIR}/rootfs/app"
-      cp "${APPDATA}/"* "${WORKDIR}/rootfs/app"
-    fi
-
-    umount "${WORKDIR}/rootfs"
-    trap "rm -rf '${WORKDIR}'" EXIT
+if [[ -z "${ROOT_DEV}" ]]; then
+    echo "Unable to find new ROOT partition on ${DEVICE}" >&2
+    exit 1
 fi
+
+mkdir -p "${WORKDIR}/rootfs"
+case $(blkid -t "LABEL=ROOT" -o value -s TYPE "${ROOT_DEV}") in
+  "btrfs") mount -t btrfs -o subvol=root "${ROOT_DEV}" "${WORKDIR}/rootfs" ;;
+  *)       mount "${ROOT_DEV}" "${WORKDIR}/rootfs" ;;
+esac
+trap "umount '${WORKDIR}/rootfs' && rm -rf '${WORKDIR}'" EXIT
+
+# resize filesystems
+echo "Resize filesystems..."
+/usr/lib64/coreos/extend-filesystems
+
+if [[ -n "${CLOUDINIT}" ]]; then
+  echo "Installing cloud-config..."
+  mkdir -p "${WORKDIR}/rootfs/var/lib/coreos-install"
+  cp "${CLOUDINIT}" "${WORKDIR}/rootfs/var/lib/coreos-install/user_data"
+fi
+
+if [[ -n "${APPDATA}" ]]; then
+  echo "Installing appdata to /app..."
+  mkdir -p "${WORKDIR}/rootfs/app"
+  cp -r "${APPDATA}/"* "${WORKDIR}/rootfs/app"
+fi
+
+umount "${WORKDIR}/rootfs"
+trap "rm -rf '${WORKDIR}'" EXIT
 
 if [[ -n "${IGNITION}" ]]; then
     # The OEM partition should be #3 but make no assumptions here!
