add support for ignition

diff --git a/src/coreos-offline-install b/src/coreos-offline-install
--- a/src/coreos-offline-install
+++ b/src/coreos-offline-install
@@ -45,6 +45,7 @@ USAGE="Usage: $0  [-d /dev/device]
 Options:
     -d DEVICE   Install CoreOS to the given device.
     -c CLOUD    Insert a cloud-init config to be executed on boot.
+    -i IGNITION Insert an Ignition config to be executed on boot.
     -a APPDATA  Install all data of this directory to /app
     -v          Super verbose, for debugging.
     -h          This ;-)
@@ -58,11 +59,12 @@ APPDATA=""
 DEVICE=""
 CLOUDINIT=""
 
-while getopts "d:c:a:vh" OPTION
+while getopts "d:c:i:a:vh" OPTION
 do
     case $OPTION in
         d) DEVICE="$OPTARG" ;;
         c) CLOUDINIT="$OPTARG" ;;
+        i) IGNITION="$OPTARG" ;;
         a) APPDATA="$OPTARG" ;;
         v) set -x ;;
         h) echo "$USAGE"; exit;;
@@ -99,6 +101,13 @@ if [[ -n "${CLOUDINIT}" ]]; then
         fi
     else
         echo "$0: coreos-cloudinit not found. Could not validate config. Continuing..." >&2
+    fi
+fi
+
+if [[ -n "${IGNITION}" ]]; then
+    if [[ ! -f "${IGNITION}" ]]; then
+        echo "$0: Ignition config file (${IGNITION}) does not exist." >&2
+        exit 1
     fi
 fi
 
@@ -150,6 +159,28 @@ if [[ -n "${CLOUDINIT}" ]]; then
     fi
 
     umount "${WORKDIR}/rootfs"
+    trap "rm -rf '${WORKDIR}'" EXIT
+fi
+
+if [[ -n "${IGNITION}" ]]; then
+    # The OEM partition should be #3 but make no assumptions here!
+    # Also don't mount by label directly in case other devices conflict.
+    OEM_DEV=$(blkid -t "LABEL=OEM" -o device "${DEVICE}"*)
+
+    if [[ -z "${OEM_DEV}" ]]; then
+      echo "Unable to find new OEM partition on ${DEVICE}" >&2
+      exit 1
+    fi
+
+    mkdir -p "${WORKDIR}/oemfs"
+    mount "${OEM_DEV}" "${WORKDIR}/oemfs"
+    trap "umount '${WORKDIR}/oemfs' && rm -rf '${WORKDIR}'" EXIT
+
+    echo "Installing Ignition config ${IGNITION}..."
+    cp "${IGNITION}" "${WORKDIR}/oemfs/coreos-install.json"
+    echo  "set linux_append=\"coreos.config.url=oem:///coreos-install.json"\" > "${WORKDIR}/oemfs/grub.cfg"
+
+    umount "${WORKDIR}/oemfs"
     trap "rm -rf '${WORKDIR}'" EXIT
 fi
 
